### ISSUE TITLE
imenu list refresh jumps to top

### ISSUE THREAD

**Issue by darrylhebbes** [bmag/imenu-list#11]
If you have a long list of items and have scrolled to the bottom of the imenu list, after a second or two, it automatically jumps back to the top.

In particular this happens with mouse scrolling, navigating with keys is working.

I get around issue using folding.

**Comment by bmag** [comment]
Hmm, I think I know what might be the problem, but I'd like to make sure first.

I'm quite sure the problem happens because imenu list refreshes itself every time you become idle for about a second, and when it refreshes it does it based on the "selected window" (the window that has the focus). In your case, it appears that you scroll the imenu list, but the indexed window is still the selected window. The reason for refreshing is so the highlighted line in the imenu list matches your position in the selected window.

Assuming you have two windows open, one for some code, the other for the imenu list, this is what I expect to happen:
- When the code window is selected, after you scroll the imenu list with the mouse, the list will refresh itself and the highlighted line will change.
  - If your position in the code window is at the top of the buffer, imenu list will jump to the top
  - If your position in the code window is at the bottom of the buffer, imenu list will jump to the bottom
- When the code window is selected, and you scroll the imenu list via <kbd>C-M-v</kbd> and <kbd>C-M-S-v</kbd> (`scroll-other-windw` and `scroll-other-window-down`), the results will be the same as when you scroll with the mouse.

Note that the location the imenu list jumps to depends on your position in the code window.

A work-around would be to click in the imenu list window before scrolling, thus making the imenu list window the selected window (imenu-list won't index its own window).

Does my description fit the behavior you're experiencing, and does the work-around solve the issue?

**Comment by darrylhebbes** [comment]
Hi, yes, thats exactly the problem.

**Comment by bmag** [comment]
Fixed version of `imenu-list` should be available via Melpa in a few hours.
I'm closing this issue, please re-open it if there is still a problem.
