### ISSUE TITLE
suggestion: make *Ilist* buffer a hidden buffer

### ISSUE THREAD

**Issue by QiangF** [bmag/imenu-list#15]
Hello,
I have this setup:
(global-set-key (kbd "C-'") 'imenu-list-minor-mode), so I can bring up or hide the *Ilist* buffer with C-'. 

Often I switch to previous file with mode-line-other-buffer. The problem appears  after I hide *Ilist* , mode-line-other-buffer switch to *Ilist*, while I want to switch to the buffer before it. I think it is unecessary to put *Ilist* on the buffer list.

Is it possbile to make "*Ilist*" hidden by changing its name to begin with a space?
Thank you for your consideration!

**Comment by bmag** [comment]
Thanks for reporting. The fix was simple and should be available from MELPA soon. When it is, can you confirm that the issue is fixed?

I've changed `imenu-list-minor-mode` to bury the buffer when toggled off. This means that when you hide *Ilist* buffer, it also goes to the end of the buffer list, so `mode-line-other-buffer` shouldn't switch to it anymore.

I decided not to make the buffer hidden, because as I understand hidden buffers are meant to never be displayed. *Ilist* is supposed to be displayed, so it's not right to make it a hidden buffer.

**Comment by QiangF** [comment]
The issue is fixed in the version in Melpa.
Thank you!
