### ISSUE TITLE
RET on list heading + error

### ISSUE THREAD

**Issue by rnkn** [bmag/imenu-list#17]
Pressing RET with point a block heading (`imenu-list-entry-subalist`) expands/collapses the entries within that heading, but pressing RET on the `+` next to a block heading results in `Invalid function: IMENU CONS`.

I think it might be more intuitive if RET on the `+` performed the same expand/collapse function, and it would avoid errors.

**Comment by rnkn** [comment]
p.s. Space also signals the same error.

**Comment by bmag** [comment]
Thanks for the report.
Each line in the imenu-list buffer corresponds to an entry in an internal data structure stored by Imenu, and pressing `RET` or `SPC` calls the entry's goto action. For some major modes (read: programming languages), the subalist entries don't have a goto action defined, hence the error. If I remember correctly, for some major modes the subalist entries do define a goto action, in which case pressing `RET` or `SPC` will jump to that entry (so no `invalid function` error for these modes). I'll double-check it and rethink about your suggestion. I'll work on this on Wednesday too.

**Comment by bmag** [comment]
Pressing RET with point at `+` next to a block heading should expand/collapse the heading now. I'm leaving the SPC issue for now, because it is a bit more complex to solve it. Basically, the call to `insert-button` that inserts the headings needs to  pass a `keymap` parameter with a suitable keymap entry that binds SPC to `hs-toggle-hiding` or `imenu-list--action-toggle-hs`. I don't know when I'll get around to it, so patch welcome :wink: 
The fixed version should be available from MELPA within several hours. If the issue (with RET) isn't fixed, feel free to reopen the issue.
