### ISSUE TITLE
why tab key enable or disable imenu-list window?

### ISSUE THREAD

**Issue by code-moritz** [bmag/imenu-list#21]
I open the imenu-list in emacs use "imenu-list-minor-mode" command. when i coding and press TAB key in coding window, the imenu-list window was disable and disappear, and presss TAB key again, the imenu-lis window enable . 

why?  i try to modify the short key binding. but not found. 

is it a bug? or has orther default setting in emacs. 

thank you

**Comment by bmag** [comment]
I don't have this problem when I use imenu-list. Since the problem happens when you press TAB in a window, not the imenu-list window, it seems to be a problem in your setup.
Can you provide more details? Anything of these can be helpful:
- a step-by-step recipe to reproduce the bug, starting with `emacs` (or even better, starting with `emacs -Q`).
- in the coding window, what is TAB bound to? Use `C-h k TAB` to find out.
- an example of the code buffer that triggers the problem
- what major mode and minor modes are enabled in the code buffer (in the coding window)? Use `C-h m` to find out.
- what is your Emacs version? Use `C-h v emacs-version` to find out.

**Comment by code-moritz** [comment]
- Start emacs with Q parmeter
- in the coding window , use c-h k tab , that show the following info
  `1TAB runs the command yas-expand, which is an alias for
  2`yas-expand-from-trigger-key' in `yasnippet.el'.
  3
  4It is bound to TAB, <tab>, <menu-bar> <YASnippet> <Expand trigger>.
  5
  6(yas-expand &optional FIELD)
  7
  8Expand a snippet before point. If no snippet
  9expansion is possible, call command`imenu-list-minor-mode'.
  10
  11Optional argument FIELD is for non-interactive use and is an
  12object satisfying `yas--field-p' to restrict the expansion to.`
- Shwo emacs version

`emacs-version is a variable defined in`C source code'.
Its value is "24.5.1"

  This variable may be risky if used as a file-local variable.

`
- Before press TAB key, the screen show

![before-tab](https://cloud.githubusercontent.com/assets/6115325/13369924/0807707a-dd37-11e5-8724-5d97b8880bc1.png)
- After press TAB key, the screen show
  ![after_tab_press](https://cloud.githubusercontent.com/assets/6115325/13369923/07d0f946-dd37-11e5-9e4f-b489be338de8.png)

**Comment by bmag** [comment]
The problem is that when it can't expand a snippet, the command `yas-expand` (from the package `yasnippet`) falls back to the command `imenu-list-minor-mode`. Usually the fallback is `indent-for-tab-command`, not `imenu-list-minor-mode`.
This could happen if you bind TAB globally to `imenu-list-minor-mode`, for example like this:

``` elisp
(global-set-key (kbd "TAB") 'imenu-list-minor-mode)
```

Can you post your configuration for yasnippet and imenu-list?

---

In a step-by-step recipe, I meant something like this:
- start emacs: `emacs -Q`
- initialize packages: `M-x package-initialize`
- evaluate this code in the scratch buffer:

```
;; ... some code that loads and configures imenu-list and yasnippet ...
```
- ... more steps as necessary ...

In this case, I think it will be enough if you post your yasnippet and imenu-list configuration, so no need for a recipe. Here's a short [explanation](http://www.lunaryorn.com/2015/11/29/reproduce-bugs-in-emacs-Q.html) about `emacs -Q`, if you're interested to know why I asked for it.

**Comment by code-moritz** [comment]
Hi, thank your reply. 
I was already try do the above steps. but the scratch buffer not additional any message.

it is only show the follow info, in meacs window.

`;; This buffer is for notes you don't want to save, and for Lisp evaluation.  
;; If you want to create a file, visit that file with C-x C-f,  
;; then enter the text in that file's own buffer.                                                   

`

if you want to check my emacs init configure file. you can visit: 
https://github.com/code-moritz/Emacs_Config/blob/master/new_dot_emacs

thank your very much.

**Comment by bmag** [comment]
In your init file, you bind imenu-list-minor-mode to "C-i". For emacs, C-i is the same as TAB, that's why Tab toggles imenu-list in your setup.

You need to change the binding, that's all.

**Comment by code-moritz** [comment]
o. that's my mistake. thank you very much. 
i am already change the global key bind and  it is ok now. 

:)

**Comment by kascesar** [comment]
> In your init file, you bind imenu-list-minor-mode to "C-i". For emacs, C-i is the same as TAB, that's why Tab toggles imenu-list in your setup.
> 
> You need to change the binding, that's all.

@bmag Thanks that was usefull :+1:
