### ISSUE TITLE
Can I automatically close the imenu-list window?

### ISSUE THREAD

**Issue by Wjinlei** [bmag/imenu-list#44]
When I use the shortcut key to call up the imenu-list, after the carriage return is selected, can I automatically close the imenu-list window, which is to automatically call imenu-list-quit-window after pressing the Enter key.

**Comment by bmag** [comment]
You can hook `imenu-list-quit-window` into `imenu-list-after-jump-hook` with `add-hook`. Unfortunately, this will close the window even if you show the entry without jumping (e.g. after pressing the Space key). As an alternative, you can advise `imenu-list-goto-entry`. Here is untested code for the two options:
```elisp
;; option 1
(add-hook 'imenu-list-after-jump-hook 'imenu-list-quit-window)

;; option 2
(add-advice 'imenu-list-goto-entry :after 'imenu-list-quit-window)
```

The advice isn't guaranteed to work for newer versions of imenu-list, but considering how little I change this package it probably will work for a long time.

Ideally you'd be able to hook into `imenu-list-after-jump-hook` a function that checks the current buffer/window and calls `imenu-list-quit-window` only when appropriate, but right now it won't work because of a technicality. It's not that hard to fix, but I'm not sure when I'll have free time to do it.

**Comment by Wjinlei** [comment]
Ok, thank you
