### ISSUE TITLE
why only 2 levels in orgmode?

### ISSUE THREAD

**Issue by VladimirAlexiev** [bmag/imenu-list#47]
I have an orgmode file with `toc:5 H:5` and 4 levels of headings.
When I cycle visibility at top of the buffer, I see all levels of headings.

However, imenu-list shows only 2 levels. It doesn't show `+` for level 2 headings with subheadings.
![image](https://user-images.githubusercontent.com/536250/53284626-b1727580-375f-11e9-8ac9-657ab8286b1f.png)

**Comment by bmag** [comment]
imenu-list shows the same index that imenu produces. When using `M-x imenu`, can you jump to a level-3 header (e.g. LinkedLifeData)? If not, then the problem is with the indexing function used by imenu.

After a short research, I found that the variable `org-imenu-depth` controls the depth of the index. By default it is set to 2, so you need to increase it in your configuration. (e.g. via `customize` interface)
