### ISSUE TITLE
Feature request: Move cursor to current item when show

### ISSUE THREAD

**Issue by Yevgnen** [bmag/imenu-list#49]
Thanks for the great package. It will be nice to move cursor to the item of current function/symbol of the origin buffer. Currently when I do `M-x imenu-list`, the cursor is sometimes in the bottom, sometimes in other places. It would be nice to have an option to move the cursor current function.

**Comment by bmag** [comment]
You can use `imenu-list-display-entry` (press `d` from the \*Ilist\* buffer) to manually move the cursor, or `imenu-list-minor-mode` or `imenu-list-smart-toggle` instead of `imenu-list` to have the cursor move automatically.

If moving manually, you'd probably want to `(setq imenu-list-after-jump-hook nil`), otherwise `imenu-list-display-entry` will also recenter the original buffer around the current entry.

**Comment by bmag** [comment]
Having `imenu-list` and `imenu-list-noselect` move the cursor after displaying the \*Ilist\* buffer would probably be a good thing too. Is that what you meant?

**Comment by Yevgnen** [comment]
`imenu-list-smart-toggle` is exactly what I want. I think I should read the README twice... Thank you very much!
