### ISSUE TITLE
Always go to "IList" window when pressing "TAB" key

### ISSUE THREAD

**Issue by andrewhit** [bmag/imenu-list#52]
Every time I press "TAB" key, the cursor always goes to "Ilist" window. And it is not desirable specially when I am writing some code.

Is there any way to avoiding this behavior?

Thanks,
Andrew

**Comment by bmag** [comment]
imenu-list only binds the TAB key in `*Ilist*` buffer. imenu-list doesn't impact the behavior of hitting TAB in other buffers.

If I understand you correctly, then the problem is that you hit TAB in some buffer (e.g. a C++ buffer) and then the focus moves to `*Ilist*` buffer. In that case, I can't help you, because the problem is caused by something else.

**Comment by andrewhit** [comment]
It seems the below key binding causes this issue within my .emacs.

`(global-set-key "\C-i" 'menu-list)
`

Then I changed it into as below and this issue is gone.

(global-set-key "\C-m" 'imenu-list)
